TRUNCATE TABLE sales_return;


SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE sales;
SET FOREIGN_KEY_CHECKS = 1;

TRUNCATE TABLE purchase_return;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE purchase;
SET FOREIGN_KEY_CHECKS = 1;